# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('parameter', models.CharField(max_length=200)),
                ('actuator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Actuator')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('parameter', models.CharField(max_length=200)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.Action')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.Event')),
            ],
        ),
    ]
