# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuator',
            name='parameters',
            field=models.ManyToManyField(to='device.Parameter'),
        ),
    ]
