# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20180323_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='value',
        ),
        migrations.AddField(
            model_name='sensor',
            name='value',
            field=models.FloatField(default=0, null=True),
        ),
    ]
