# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_auto_20180323_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
