# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_auto_20180323_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actuator',
            old_name='parameters',
            new_name='actions',
        ),
        migrations.AddField(
            model_name='sensor',
            name='events',
            field=models.ManyToManyField(to='device.Parameter'),
        ),
    ]
