# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_device_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='variable',
            field=models.BooleanField(default=False),
        ),
    ]
